// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// rcdb_new
SEXP rcdb_new(std::string name);
RcppExport SEXP _rcantordb_rcdb_new(SEXP nameSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type name(nameSEXP);
    rcpp_result_gen = Rcpp::wrap(rcdb_new(name));
    return rcpp_result_gen;
END_RCPP
}
// rcdb_load
SEXP rcdb_load(std::string path);
RcppExport SEXP _rcantordb_rcdb_load(SEXP pathSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type path(pathSEXP);
    rcpp_result_gen = Rcpp::wrap(rcdb_load(path));
    return rcpp_result_gen;
END_RCPP
}
// rcdb_save
bool rcdb_save(SEXP db_ptr, std::string path);
RcppExport SEXP _rcantordb_rcdb_save(SEXP db_ptrSEXP, SEXP pathSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type db_ptr(db_ptrSEXP);
    Rcpp::traits::input_parameter< std::string >::type path(pathSEXP);
    rcpp_result_gen = Rcpp::wrap(rcdb_save(db_ptr, path));
    return rcpp_result_gen;
END_RCPP
}
// rcdb_create_set
bool rcdb_create_set(SEXP db_ptr, std::string set_name);
RcppExport SEXP _rcantordb_rcdb_create_set(SEXP db_ptrSEXP, SEXP set_nameSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type db_ptr(db_ptrSEXP);
    Rcpp::traits::input_parameter< std::string >::type set_name(set_nameSEXP);
    rcpp_result_gen = Rcpp::wrap(rcdb_create_set(db_ptr, set_name));
    return rcpp_result_gen;
END_RCPP
}
// rcdb_delete_set
bool rcdb_delete_set(SEXP db_ptr, std::string set_name);
RcppExport SEXP _rcantordb_rcdb_delete_set(SEXP db_ptrSEXP, SEXP set_nameSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type db_ptr(db_ptrSEXP);
    Rcpp::traits::input_parameter< std::string >::type set_name(set_nameSEXP);
    rcpp_result_gen = Rcpp::wrap(rcdb_delete_set(db_ptr, set_name));
    return rcpp_result_gen;
END_RCPP
}
// rcdb_rename_set
bool rcdb_rename_set(SEXP db_ptr, std::string set_name, std::string new_name);
RcppExport SEXP _rcantordb_rcdb_rename_set(SEXP db_ptrSEXP, SEXP set_nameSEXP, SEXP new_nameSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type db_ptr(db_ptrSEXP);
    Rcpp::traits::input_parameter< std::string >::type set_name(set_nameSEXP);
    Rcpp::traits::input_parameter< std::string >::type new_name(new_nameSEXP);
    rcpp_result_gen = Rcpp::wrap(rcdb_rename_set(db_ptr, set_name, new_name));
    return rcpp_result_gen;
END_RCPP
}
// rcdb_add_member
bool rcdb_add_member(SEXP db_ptr, std::string set_name, std::string element_name);
RcppExport SEXP _rcantordb_rcdb_add_member(SEXP db_ptrSEXP, SEXP set_nameSEXP, SEXP element_nameSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type db_ptr(db_ptrSEXP);
    Rcpp::traits::input_parameter< std::string >::type set_name(set_nameSEXP);
    Rcpp::traits::input_parameter< std::string >::type element_name(element_nameSEXP);
    rcpp_result_gen = Rcpp::wrap(rcdb_add_member(db_ptr, set_name, element_name));
    return rcpp_result_gen;
END_RCPP
}
// rcdb_remove_member
bool rcdb_remove_member(SEXP db_ptr, std::string set_name, std::string element_name);
RcppExport SEXP _rcantordb_rcdb_remove_member(SEXP db_ptrSEXP, SEXP set_nameSEXP, SEXP element_nameSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type db_ptr(db_ptrSEXP);
    Rcpp::traits::input_parameter< std::string >::type set_name(set_nameSEXP);
    Rcpp::traits::input_parameter< std::string >::type element_name(element_nameSEXP);
    rcpp_result_gen = Rcpp::wrap(rcdb_remove_member(db_ptr, set_name, element_name));
    return rcpp_result_gen;
END_RCPP
}
// rcdb_add_property_int
bool rcdb_add_property_int(SEXP db_ptr, std::string key, int value, std::string set_name);
RcppExport SEXP _rcantordb_rcdb_add_property_int(SEXP db_ptrSEXP, SEXP keySEXP, SEXP valueSEXP, SEXP set_nameSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type db_ptr(db_ptrSEXP);
    Rcpp::traits::input_parameter< std::string >::type key(keySEXP);
    Rcpp::traits::input_parameter< int >::type value(valueSEXP);
    Rcpp::traits::input_parameter< std::string >::type set_name(set_nameSEXP);
    rcpp_result_gen = Rcpp::wrap(rcdb_add_property_int(db_ptr, key, value, set_name));
    return rcpp_result_gen;
END_RCPP
}
// rcdb_add_property_string
bool rcdb_add_property_string(SEXP db_ptr, std::string key, std::string value, std::string set_name);
RcppExport SEXP _rcantordb_rcdb_add_property_string(SEXP db_ptrSEXP, SEXP keySEXP, SEXP valueSEXP, SEXP set_nameSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type db_ptr(db_ptrSEXP);
    Rcpp::traits::input_parameter< std::string >::type key(keySEXP);
    Rcpp::traits::input_parameter< std::string >::type value(valueSEXP);
    Rcpp::traits::input_parameter< std::string >::type set_name(set_nameSEXP);
    rcpp_result_gen = Rcpp::wrap(rcdb_add_property_string(db_ptr, key, value, set_name));
    return rcpp_result_gen;
END_RCPP
}
// rcdb_add_property_double
bool rcdb_add_property_double(SEXP db_ptr, std::string key, double value, std::string set_name);
RcppExport SEXP _rcantordb_rcdb_add_property_double(SEXP db_ptrSEXP, SEXP keySEXP, SEXP valueSEXP, SEXP set_nameSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type db_ptr(db_ptrSEXP);
    Rcpp::traits::input_parameter< std::string >::type key(keySEXP);
    Rcpp::traits::input_parameter< double >::type value(valueSEXP);
    Rcpp::traits::input_parameter< std::string >::type set_name(set_nameSEXP);
    rcpp_result_gen = Rcpp::wrap(rcdb_add_property_double(db_ptr, key, value, set_name));
    return rcpp_result_gen;
END_RCPP
}
// rcdb_add_property_bool
bool rcdb_add_property_bool(SEXP db_ptr, std::string key, bool value, std::string set_name);
RcppExport SEXP _rcantordb_rcdb_add_property_bool(SEXP db_ptrSEXP, SEXP keySEXP, SEXP valueSEXP, SEXP set_nameSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type db_ptr(db_ptrSEXP);
    Rcpp::traits::input_parameter< std::string >::type key(keySEXP);
    Rcpp::traits::input_parameter< bool >::type value(valueSEXP);
    Rcpp::traits::input_parameter< std::string >::type set_name(set_nameSEXP);
    rcpp_result_gen = Rcpp::wrap(rcdb_add_property_bool(db_ptr, key, value, set_name));
    return rcpp_result_gen;
END_RCPP
}
// rcdb_delete_property
bool rcdb_delete_property(SEXP db_ptr, std::string set_name, std::string key_name);
RcppExport SEXP _rcantordb_rcdb_delete_property(SEXP db_ptrSEXP, SEXP set_nameSEXP, SEXP key_nameSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type db_ptr(db_ptrSEXP);
    Rcpp::traits::input_parameter< std::string >::type set_name(set_nameSEXP);
    Rcpp::traits::input_parameter< std::string >::type key_name(key_nameSEXP);
    rcpp_result_gen = Rcpp::wrap(rcdb_delete_property(db_ptr, set_name, key_name));
    return rcpp_result_gen;
END_RCPP
}
// rcdb_update_property_int
bool rcdb_update_property_int(SEXP db_ptr, std::string set_name, std::string key, int value);
RcppExport SEXP _rcantordb_rcdb_update_property_int(SEXP db_ptrSEXP, SEXP set_nameSEXP, SEXP keySEXP, SEXP valueSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type db_ptr(db_ptrSEXP);
    Rcpp::traits::input_parameter< std::string >::type set_name(set_nameSEXP);
    Rcpp::traits::input_parameter< std::string >::type key(keySEXP);
    Rcpp::traits::input_parameter< int >::type value(valueSEXP);
    rcpp_result_gen = Rcpp::wrap(rcdb_update_property_int(db_ptr, set_name, key, value));
    return rcpp_result_gen;
END_RCPP
}
// rcdb_update_property_string
bool rcdb_update_property_string(SEXP db_ptr, std::string set_name, std::string key, std::string value);
RcppExport SEXP _rcantordb_rcdb_update_property_string(SEXP db_ptrSEXP, SEXP set_nameSEXP, SEXP keySEXP, SEXP valueSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type db_ptr(db_ptrSEXP);
    Rcpp::traits::input_parameter< std::string >::type set_name(set_nameSEXP);
    Rcpp::traits::input_parameter< std::string >::type key(keySEXP);
    Rcpp::traits::input_parameter< std::string >::type value(valueSEXP);
    rcpp_result_gen = Rcpp::wrap(rcdb_update_property_string(db_ptr, set_name, key, value));
    return rcpp_result_gen;
END_RCPP
}
// rcdb_update_property_double
bool rcdb_update_property_double(SEXP db_ptr, std::string set_name, std::string key, double value);
RcppExport SEXP _rcantordb_rcdb_update_property_double(SEXP db_ptrSEXP, SEXP set_nameSEXP, SEXP keySEXP, SEXP valueSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type db_ptr(db_ptrSEXP);
    Rcpp::traits::input_parameter< std::string >::type set_name(set_nameSEXP);
    Rcpp::traits::input_parameter< std::string >::type key(keySEXP);
    Rcpp::traits::input_parameter< double >::type value(valueSEXP);
    rcpp_result_gen = Rcpp::wrap(rcdb_update_property_double(db_ptr, set_name, key, value));
    return rcpp_result_gen;
END_RCPP
}
// rcdb_update_property_bool
bool rcdb_update_property_bool(SEXP db_ptr, std::string set_name, std::string key, bool value);
RcppExport SEXP _rcantordb_rcdb_update_property_bool(SEXP db_ptrSEXP, SEXP set_nameSEXP, SEXP keySEXP, SEXP valueSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type db_ptr(db_ptrSEXP);
    Rcpp::traits::input_parameter< std::string >::type set_name(set_nameSEXP);
    Rcpp::traits::input_parameter< std::string >::type key(keySEXP);
    Rcpp::traits::input_parameter< bool >::type value(valueSEXP);
    rcpp_result_gen = Rcpp::wrap(rcdb_update_property_bool(db_ptr, set_name, key, value));
    return rcpp_result_gen;
END_RCPP
}
// rcdb_get_property
List rcdb_get_property(SEXP db_ptr, std::string set_name, std::string key_name);
RcppExport SEXP _rcantordb_rcdb_get_property(SEXP db_ptrSEXP, SEXP set_nameSEXP, SEXP key_nameSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type db_ptr(db_ptrSEXP);
    Rcpp::traits::input_parameter< std::string >::type set_name(set_nameSEXP);
    Rcpp::traits::input_parameter< std::string >::type key_name(key_nameSEXP);
    rcpp_result_gen = Rcpp::wrap(rcdb_get_property(db_ptr, set_name, key_name));
    return rcpp_result_gen;
END_RCPP
}
// rcdb_list_elements
CharacterVector rcdb_list_elements(SEXP db_ptr, std::string set_name);
RcppExport SEXP _rcantordb_rcdb_list_elements(SEXP db_ptrSEXP, SEXP set_nameSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type db_ptr(db_ptrSEXP);
    Rcpp::traits::input_parameter< std::string >::type set_name(set_nameSEXP);
    rcpp_result_gen = Rcpp::wrap(rcdb_list_elements(db_ptr, set_name));
    return rcpp_result_gen;
END_RCPP
}
// rcdb_list_all_sets
CharacterVector rcdb_list_all_sets(SEXP db_ptr);
RcppExport SEXP _rcantordb_rcdb_list_all_sets(SEXP db_ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type db_ptr(db_ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(rcdb_list_all_sets(db_ptr));
    return rcpp_result_gen;
END_RCPP
}
// rcdb_list_cached_sets
CharacterVector rcdb_list_cached_sets(SEXP db_ptr);
RcppExport SEXP _rcantordb_rcdb_list_cached_sets(SEXP db_ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type db_ptr(db_ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(rcdb_list_cached_sets(db_ptr));
    return rcpp_result_gen;
END_RCPP
}
// rcdb_list_properties
DataFrame rcdb_list_properties(SEXP db_ptr, std::string set_name);
RcppExport SEXP _rcantordb_rcdb_list_properties(SEXP db_ptrSEXP, SEXP set_nameSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type db_ptr(db_ptrSEXP);
    Rcpp::traits::input_parameter< std::string >::type set_name(set_nameSEXP);
    rcpp_result_gen = Rcpp::wrap(rcdb_list_properties(db_ptr, set_name));
    return rcpp_result_gen;
END_RCPP
}
// rcdb_list_property_keys
DataFrame rcdb_list_property_keys(SEXP db_ptr, std::string set_name);
RcppExport SEXP _rcantordb_rcdb_list_property_keys(SEXP db_ptrSEXP, SEXP set_nameSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type db_ptr(db_ptrSEXP);
    Rcpp::traits::input_parameter< std::string >::type set_name(set_nameSEXP);
    rcpp_result_gen = Rcpp::wrap(rcdb_list_property_keys(db_ptr, set_name));
    return rcpp_result_gen;
END_RCPP
}
// rcdb_list_typed_properties
DataFrame rcdb_list_typed_properties(SEXP db_ptr, std::string set_name, std::string type);
RcppExport SEXP _rcantordb_rcdb_list_typed_properties(SEXP db_ptrSEXP, SEXP set_nameSEXP, SEXP typeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type db_ptr(db_ptrSEXP);
    Rcpp::traits::input_parameter< std::string >::type set_name(set_nameSEXP);
    Rcpp::traits::input_parameter< std::string >::type type(typeSEXP);
    rcpp_result_gen = Rcpp::wrap(rcdb_list_typed_properties(db_ptr, set_name, type));
    return rcpp_result_gen;
END_RCPP
}
// rcdb_get_cardinality
int rcdb_get_cardinality(SEXP db_ptr, std::string set_name);
RcppExport SEXP _rcantordb_rcdb_get_cardinality(SEXP db_ptrSEXP, SEXP set_nameSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type db_ptr(db_ptrSEXP);
    Rcpp::traits::input_parameter< std::string >::type set_name(set_nameSEXP);
    rcpp_result_gen = Rcpp::wrap(rcdb_get_cardinality(db_ptr, set_name));
    return rcpp_result_gen;
END_RCPP
}
// rcdb_set_union
SEXP rcdb_set_union(SEXP db_ptr, std::string a, std::string b);
RcppExport SEXP _rcantordb_rcdb_set_union(SEXP db_ptrSEXP, SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type db_ptr(db_ptrSEXP);
    Rcpp::traits::input_parameter< std::string >::type a(aSEXP);
    Rcpp::traits::input_parameter< std::string >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(rcdb_set_union(db_ptr, a, b));
    return rcpp_result_gen;
END_RCPP
}
// rcdb_set_intersection
SEXP rcdb_set_intersection(SEXP db_ptr, std::string a, std::string b);
RcppExport SEXP _rcantordb_rcdb_set_intersection(SEXP db_ptrSEXP, SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type db_ptr(db_ptrSEXP);
    Rcpp::traits::input_parameter< std::string >::type a(aSEXP);
    Rcpp::traits::input_parameter< std::string >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(rcdb_set_intersection(db_ptr, a, b));
    return rcpp_result_gen;
END_RCPP
}
// rcdb_set_difference
SEXP rcdb_set_difference(SEXP db_ptr, std::string a, std::string b);
RcppExport SEXP _rcantordb_rcdb_set_difference(SEXP db_ptrSEXP, SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type db_ptr(db_ptrSEXP);
    Rcpp::traits::input_parameter< std::string >::type a(aSEXP);
    Rcpp::traits::input_parameter< std::string >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(rcdb_set_difference(db_ptr, a, b));
    return rcpp_result_gen;
END_RCPP
}
// rcdb_symmetric_difference
SEXP rcdb_symmetric_difference(SEXP db_ptr, std::string a, std::string b);
RcppExport SEXP _rcantordb_rcdb_symmetric_difference(SEXP db_ptrSEXP, SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type db_ptr(db_ptrSEXP);
    Rcpp::traits::input_parameter< std::string >::type a(aSEXP);
    Rcpp::traits::input_parameter< std::string >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(rcdb_symmetric_difference(db_ptr, a, b));
    return rcpp_result_gen;
END_RCPP
}
// rcdb_set_complement
SEXP rcdb_set_complement(SEXP db_ptr, std::string set_name);
RcppExport SEXP _rcantordb_rcdb_set_complement(SEXP db_ptrSEXP, SEXP set_nameSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type db_ptr(db_ptrSEXP);
    Rcpp::traits::input_parameter< std::string >::type set_name(set_nameSEXP);
    rcpp_result_gen = Rcpp::wrap(rcdb_set_complement(db_ptr, set_name));
    return rcpp_result_gen;
END_RCPP
}
// rcdb_is_subset
bool rcdb_is_subset(SEXP db_ptr, std::string a, std::string b);
RcppExport SEXP _rcantordb_rcdb_is_subset(SEXP db_ptrSEXP, SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type db_ptr(db_ptrSEXP);
    Rcpp::traits::input_parameter< std::string >::type a(aSEXP);
    Rcpp::traits::input_parameter< std::string >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(rcdb_is_subset(db_ptr, a, b));
    return rcpp_result_gen;
END_RCPP
}
// rcdb_is_superset
bool rcdb_is_superset(SEXP db_ptr, std::string a, std::string b);
RcppExport SEXP _rcantordb_rcdb_is_superset(SEXP db_ptrSEXP, SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type db_ptr(db_ptrSEXP);
    Rcpp::traits::input_parameter< std::string >::type a(aSEXP);
    Rcpp::traits::input_parameter< std::string >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(rcdb_is_superset(db_ptr, a, b));
    return rcpp_result_gen;
END_RCPP
}
// rcdb_is_disjoint
bool rcdb_is_disjoint(SEXP db_ptr, std::string a, std::string b);
RcppExport SEXP _rcantordb_rcdb_is_disjoint(SEXP db_ptrSEXP, SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type db_ptr(db_ptrSEXP);
    Rcpp::traits::input_parameter< std::string >::type a(aSEXP);
    Rcpp::traits::input_parameter< std::string >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(rcdb_is_disjoint(db_ptr, a, b));
    return rcpp_result_gen;
END_RCPP
}
// rcdb_is_equal
bool rcdb_is_equal(SEXP db_ptr, std::string a, std::string b);
RcppExport SEXP _rcantordb_rcdb_is_equal(SEXP db_ptrSEXP, SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type db_ptr(db_ptrSEXP);
    Rcpp::traits::input_parameter< std::string >::type a(aSEXP);
    Rcpp::traits::input_parameter< std::string >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(rcdb_is_equal(db_ptr, a, b));
    return rcpp_result_gen;
END_RCPP
}
// rcdb_clear_cache
bool rcdb_clear_cache(SEXP db_ptr);
RcppExport SEXP _rcantordb_rcdb_clear_cache(SEXP db_ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type db_ptr(db_ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(rcdb_clear_cache(db_ptr));
    return rcpp_result_gen;
END_RCPP
}
// rcdb_name
std::string rcdb_name(SEXP db_ptr);
RcppExport SEXP _rcantordb_rcdb_name(SEXP db_ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type db_ptr(db_ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(rcdb_name(db_ptr));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_rcantordb_rcdb_new", (DL_FUNC) &_rcantordb_rcdb_new, 1},
    {"_rcantordb_rcdb_load", (DL_FUNC) &_rcantordb_rcdb_load, 1},
    {"_rcantordb_rcdb_save", (DL_FUNC) &_rcantordb_rcdb_save, 2},
    {"_rcantordb_rcdb_create_set", (DL_FUNC) &_rcantordb_rcdb_create_set, 2},
    {"_rcantordb_rcdb_delete_set", (DL_FUNC) &_rcantordb_rcdb_delete_set, 2},
    {"_rcantordb_rcdb_rename_set", (DL_FUNC) &_rcantordb_rcdb_rename_set, 3},
    {"_rcantordb_rcdb_add_member", (DL_FUNC) &_rcantordb_rcdb_add_member, 3},
    {"_rcantordb_rcdb_remove_member", (DL_FUNC) &_rcantordb_rcdb_remove_member, 3},
    {"_rcantordb_rcdb_add_property_int", (DL_FUNC) &_rcantordb_rcdb_add_property_int, 4},
    {"_rcantordb_rcdb_add_property_string", (DL_FUNC) &_rcantordb_rcdb_add_property_string, 4},
    {"_rcantordb_rcdb_add_property_double", (DL_FUNC) &_rcantordb_rcdb_add_property_double, 4},
    {"_rcantordb_rcdb_add_property_bool", (DL_FUNC) &_rcantordb_rcdb_add_property_bool, 4},
    {"_rcantordb_rcdb_delete_property", (DL_FUNC) &_rcantordb_rcdb_delete_property, 3},
    {"_rcantordb_rcdb_update_property_int", (DL_FUNC) &_rcantordb_rcdb_update_property_int, 4},
    {"_rcantordb_rcdb_update_property_string", (DL_FUNC) &_rcantordb_rcdb_update_property_string, 4},
    {"_rcantordb_rcdb_update_property_double", (DL_FUNC) &_rcantordb_rcdb_update_property_double, 4},
    {"_rcantordb_rcdb_update_property_bool", (DL_FUNC) &_rcantordb_rcdb_update_property_bool, 4},
    {"_rcantordb_rcdb_get_property", (DL_FUNC) &_rcantordb_rcdb_get_property, 3},
    {"_rcantordb_rcdb_list_elements", (DL_FUNC) &_rcantordb_rcdb_list_elements, 2},
    {"_rcantordb_rcdb_list_all_sets", (DL_FUNC) &_rcantordb_rcdb_list_all_sets, 1},
    {"_rcantordb_rcdb_list_cached_sets", (DL_FUNC) &_rcantordb_rcdb_list_cached_sets, 1},
    {"_rcantordb_rcdb_list_properties", (DL_FUNC) &_rcantordb_rcdb_list_properties, 2},
    {"_rcantordb_rcdb_list_property_keys", (DL_FUNC) &_rcantordb_rcdb_list_property_keys, 2},
    {"_rcantordb_rcdb_list_typed_properties", (DL_FUNC) &_rcantordb_rcdb_list_typed_properties, 3},
    {"_rcantordb_rcdb_get_cardinality", (DL_FUNC) &_rcantordb_rcdb_get_cardinality, 2},
    {"_rcantordb_rcdb_set_union", (DL_FUNC) &_rcantordb_rcdb_set_union, 3},
    {"_rcantordb_rcdb_set_intersection", (DL_FUNC) &_rcantordb_rcdb_set_intersection, 3},
    {"_rcantordb_rcdb_set_difference", (DL_FUNC) &_rcantordb_rcdb_set_difference, 3},
    {"_rcantordb_rcdb_symmetric_difference", (DL_FUNC) &_rcantordb_rcdb_symmetric_difference, 3},
    {"_rcantordb_rcdb_set_complement", (DL_FUNC) &_rcantordb_rcdb_set_complement, 2},
    {"_rcantordb_rcdb_is_subset", (DL_FUNC) &_rcantordb_rcdb_is_subset, 3},
    {"_rcantordb_rcdb_is_superset", (DL_FUNC) &_rcantordb_rcdb_is_superset, 3},
    {"_rcantordb_rcdb_is_disjoint", (DL_FUNC) &_rcantordb_rcdb_is_disjoint, 3},
    {"_rcantordb_rcdb_is_equal", (DL_FUNC) &_rcantordb_rcdb_is_equal, 3},
    {"_rcantordb_rcdb_clear_cache", (DL_FUNC) &_rcantordb_rcdb_clear_cache, 1},
    {"_rcantordb_rcdb_name", (DL_FUNC) &_rcantordb_rcdb_name, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_rcantordb(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
