# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcdb_new <- function(name) {
    .Call(`_rcantordb_rcdb_new`, name)
}

rcdb_load <- function(path) {
    .Call(`_rcantordb_rcdb_load`, path)
}

rcdb_save <- function(db_ptr, path) {
    .Call(`_rcantordb_rcdb_save`, db_ptr, path)
}

rcdb_create_set <- function(db_ptr, set_name) {
    .Call(`_rcantordb_rcdb_create_set`, db_ptr, set_name)
}

rcdb_delete_set <- function(db_ptr, set_name) {
    .Call(`_rcantordb_rcdb_delete_set`, db_ptr, set_name)
}

rcdb_rename_set <- function(db_ptr, set_name, new_name) {
    .Call(`_rcantordb_rcdb_rename_set`, db_ptr, set_name, new_name)
}

rcdb_add_member <- function(db_ptr, set_name, element_name) {
    .Call(`_rcantordb_rcdb_add_member`, db_ptr, set_name, element_name)
}

rcdb_remove_member <- function(db_ptr, set_name, element_name) {
    .Call(`_rcantordb_rcdb_remove_member`, db_ptr, set_name, element_name)
}

rcdb_add_property_int <- function(db_ptr, key, value, set_name) {
    .Call(`_rcantordb_rcdb_add_property_int`, db_ptr, key, value, set_name)
}

rcdb_add_property_string <- function(db_ptr, key, value, set_name) {
    .Call(`_rcantordb_rcdb_add_property_string`, db_ptr, key, value, set_name)
}

rcdb_add_property_double <- function(db_ptr, key, value, set_name) {
    .Call(`_rcantordb_rcdb_add_property_double`, db_ptr, key, value, set_name)
}

rcdb_add_property_bool <- function(db_ptr, key, value, set_name) {
    .Call(`_rcantordb_rcdb_add_property_bool`, db_ptr, key, value, set_name)
}

rcdb_delete_property <- function(db_ptr, set_name, key_name) {
    .Call(`_rcantordb_rcdb_delete_property`, db_ptr, set_name, key_name)
}

rcdb_update_property_int <- function(db_ptr, set_name, key, value) {
    .Call(`_rcantordb_rcdb_update_property_int`, db_ptr, set_name, key, value)
}

rcdb_update_property_string <- function(db_ptr, set_name, key, value) {
    .Call(`_rcantordb_rcdb_update_property_string`, db_ptr, set_name, key, value)
}

rcdb_update_property_double <- function(db_ptr, set_name, key, value) {
    .Call(`_rcantordb_rcdb_update_property_double`, db_ptr, set_name, key, value)
}

rcdb_update_property_bool <- function(db_ptr, set_name, key, value) {
    .Call(`_rcantordb_rcdb_update_property_bool`, db_ptr, set_name, key, value)
}

rcdb_get_property <- function(db_ptr, set_name, key_name) {
    .Call(`_rcantordb_rcdb_get_property`, db_ptr, set_name, key_name)
}

rcdb_list_elements <- function(db_ptr, set_name) {
    .Call(`_rcantordb_rcdb_list_elements`, db_ptr, set_name)
}

rcdb_list_all_sets <- function(db_ptr) {
    .Call(`_rcantordb_rcdb_list_all_sets`, db_ptr)
}

rcdb_list_cached_sets <- function(db_ptr) {
    .Call(`_rcantordb_rcdb_list_cached_sets`, db_ptr)
}

rcdb_list_properties <- function(db_ptr, set_name) {
    .Call(`_rcantordb_rcdb_list_properties`, db_ptr, set_name)
}

rcdb_list_property_keys <- function(db_ptr, set_name) {
    .Call(`_rcantordb_rcdb_list_property_keys`, db_ptr, set_name)
}

rcdb_list_typed_properties <- function(db_ptr, set_name, type) {
    .Call(`_rcantordb_rcdb_list_typed_properties`, db_ptr, set_name, type)
}

rcdb_get_cardinality <- function(db_ptr, set_name) {
    .Call(`_rcantordb_rcdb_get_cardinality`, db_ptr, set_name)
}

rcdb_set_union <- function(db_ptr, a, b) {
    .Call(`_rcantordb_rcdb_set_union`, db_ptr, a, b)
}

rcdb_set_intersection <- function(db_ptr, a, b) {
    .Call(`_rcantordb_rcdb_set_intersection`, db_ptr, a, b)
}

rcdb_set_difference <- function(db_ptr, a, b) {
    .Call(`_rcantordb_rcdb_set_difference`, db_ptr, a, b)
}

rcdb_symmetric_difference <- function(db_ptr, a, b) {
    .Call(`_rcantordb_rcdb_symmetric_difference`, db_ptr, a, b)
}

rcdb_set_complement <- function(db_ptr, set_name) {
    .Call(`_rcantordb_rcdb_set_complement`, db_ptr, set_name)
}

rcdb_is_subset <- function(db_ptr, a, b) {
    .Call(`_rcantordb_rcdb_is_subset`, db_ptr, a, b)
}

rcdb_is_superset <- function(db_ptr, a, b) {
    .Call(`_rcantordb_rcdb_is_superset`, db_ptr, a, b)
}

rcdb_is_disjoint <- function(db_ptr, a, b) {
    .Call(`_rcantordb_rcdb_is_disjoint`, db_ptr, a, b)
}

rcdb_is_equal <- function(db_ptr, a, b) {
    .Call(`_rcantordb_rcdb_is_equal`, db_ptr, a, b)
}

rcdb_clear_cache <- function(db_ptr) {
    .Call(`_rcantordb_rcdb_clear_cache`, db_ptr)
}

rcdb_name <- function(db_ptr) {
    .Call(`_rcantordb_rcdb_name`, db_ptr)
}

