#ifndef PARSER_H
#define PARSER_H

#include "lexer.h"

enum QueryType {ELEMENTS, SETS, ALL_SETS, CACHE_SETS, IS, ERR, CREATE, DELETE, DELETE_HARSH, ADD_ELEM, REMOVE_ELEM, ADD_PROPERTY, REMOVE_PROPERTY, CREATE_PROPERTY, CARDINALITY, PROPERTIES, UPDATE, RENAME_SET, RENAME_PROPERTY, CLEAR_CACHE, COMPLEMENT, SAVE, LOAD, KEYS, GET_PROPERTY, RESTORE};

enum ParserErrorCode {PE_NONE, PE_SYNTAX, PE_NO_GET, PE_FILE_NF};

string parse_query(cantordb& db, const string& query);

#endif
